language: cpp

sudo: required

dist: xenial

compiler:
  - gcc

os:
  - linux

before_install:
  - echo $LC_ALL

script:
  - cd tests/ && make

after_success:

branches:
  only:
    - master
    - "/^v\\d+\\./"
notifications:
email: false
